name: opensearch_dart
description: Opensearch bindings for Dart and Flutter
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.1 <4.0.0'

dependencies:
  openapi_generator_annotations: ^4.13.0

dev_dependencies:
  lints: ^2.0.0
  openapi_generator: ^4.13.0
  build_runner: ^2.4.6
