name: CI

on:
  push:
    paths-ignore:
      - '*.md'
      - '*.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y make
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install OpenSearch
        uses: ankane/setup-opensearch@v1
        with:
          opensearch-version: 2.3.0
      - name: Run Tests
        run: make unit-tests
      - name: Archive coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-coverage.info
          path: coverage/lcov.info
